### ISSUE TITLE
Mkfifo pipe failed

### ISSUE THREAD

**Issue by Flopsing** [pink-room/fastlane-plugin-run_tests_firebase_testlab#11]
If a testlab run has failed, for example because the provided app_apk path was wrong the plugin exits with:

>Exit status of command 'tee instrumentation_output.txt < pipe & gcloud firebase test android run --type instrumentation --app /app/build/outputs/apk/yourapp/debug/app-yourapp-debug.apk --test /app/build/outputs/apk/androidTest/yourapp/debug/app-yourapp-debug-androidTest.apk --device model=Pixel2,version=27,locale=de_DE,orientation=portrait --timeout 30m  > pipe 2>&1' was 1 instead of 0. (FastlaneCore::Interface::FastlaneShellError) 
.....
Uploading [/app/build/outputs/apk/yourapp/debug/app-yourapp-debug.apk] to Firebase Test Lab...
ERROR: (gcloud.firebase.test.android.run) [/app/build/outputs/apk/yourapp/debug/app-yourapp-debug.apk] not found or not accessible

In this case Action.sh("rm pipe") is not getting executed and therefore the pipe is not removed.
If you then provide the correct apk path and run fastlane again, you will get the following error:

> [!] Exit status of command 'mkfifo pipe' was 1 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
mkfifo: cannot create fifo 'pipe': File exists

I'm not sure what the best solution is to fix this.  Either check if the file already exists and if so, remove it before calling Action.sh("mkfifo pipe") or a better handling of the gloud firebase test error to make sure 
Action.sh("rm pipe") is called regardless of whether gloucd test failed or not.

Kind regards
Flopsing

**Comment by bffcorreia** [comment]
Hi @Flopsing,

Thanks for your issue report. 

Your solutions look good. I will try to fix it as soon as possible :) 

Cheers

**Comment by alistairholmes** [comment]
I'm facing the same issue as @Flopsing . I just setup my environment and tried running the testlab but I'm getting ```[!] Exit status of command 'mkfifo pipe' was 1 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
mkfifo: cannot create fifo 'pipe': File exists```

**Comment by bffcorreia** [comment]
Sorry for the delay, I will try to fix it until the end of the week.

**Comment by bffcorreia** [comment]
Fixed in version [0.2.1](https://rubygems.org/gems/fastlane-plugin-run_tests_firebase_testlab/versions/0.2.1). Feel free to open the issue if something is wrong.

**Comment by alistairholmes** [comment]
Thank you :)
