### ISSUE TITLE
Rename parameter should_download_from_firebase to download_results_from_firebase

### ISSUE THREAD

**Issue by wevnasc** [pink-room/fastlane-plugin-run_tests_firebase_testlab#17]
the parameter should_download_from_firebase not work, the parameter should be renamed to download_results_from_firebase in README.md

**Comment by bffcorreia** [comment]
The [README](https://github.com/pink-room/fastlane-plugin-run_tests_firebase_testlab#parameters) is now updated. Thanks @wnascimentto!
