### ISSUE TITLE
Issue with Travis CI  , gcloud and Fastlane

### ISSUE THREAD

**Issue by moatazeldebsy** [pink-room/fastlane-plugin-run_tests_firebase_testlab#19]
I got the following error when trying to run the tests on Firebase Test Lab using Fastlane and gcloud 

/home/travis/.rvm/gems/ruby-2.4.1/gems/fastlane-2.116.1/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': [!] Exit status of command 'tee instrumentation_output.txt < testlab-pipe & gcloud firebase test android run --type instrumentation --app ./app/build/outputs/apk/[apk file] --test ./app/build/outputs/apk/androidTest/[test.apk] --device model=walleye,version=27,locale=en_US,orientation=portrait --timeout 30m  > testlab-pipe 2>&1' was 1 instead of 0. (FastlaneCore::Interface::FastlaneShellError)

**Comment by bffcorreia** [comment]
Hi @moatazeldebsy!

You only get that info in the stack trace?

Btw, can you `ssh` the travis machine and test if you have the `gcloud` and `tee` commands?

Cheers

**Comment by moatazeldebsy** [comment]
@bffcorreia Thank you for your help I solved it

**Comment by ahanusek** [comment]
I have similar issue on Bitrise (CI/CD). My workflow always throw an error:

```[12:28:26]: --- Step: run_tests_firebase_testlab ---
[12:28:26]: ----------------------------------------
[12:28:26]: Starting run_tests_firebase_testlab plugin...
[12:28:26]: Set Google Cloud target project.
[12:28:26]: $ gcloud config set project my-project-name
**[12:28:26]: No such file or directory - gcloud**
```

Even if in the step before I added manual gcloud installation, fastlane somehow doesn't have access to this command. Locally everything is fine.

**Comment by bffcorreia** [comment]
Hey @ahanusek!

Which stack are you using to run your workflows? Apparently, the `gcloud` is installed in the Ubuntu stacks. Check [this](https://discuss.bitrise.io/t/add-google-cloud-cli-gcloud-gsutil-to-mac-stacks/8581).

If after manual installation you can't use the `gcloud` command, it's probably just because you don't have it in you `PATH`.

Hope it helps :)

**Comment by ahanusek** [comment]
Thanks, switching to Ubuntu stack solved my issue.
