### ISSUE TITLE
client-secret.json file is content is overwritten when i run firebase instrumentation tests lane

### ISSUE THREAD

**Issue by osborneomuya** [pink-room/fastlane-plugin-run_tests_firebase_testlab#24]
I am using fastlane to run instrumentation tests on firebase test lab.when i run the command "`bundle _exec fastlane instrumentation_tests_testlab`_" i get the error "(gcloud.auth.activate-service-account) Could not read json file client-secret.json: No JSON object could be decoded" and the contents of the client-secret.json file that i had in my project root are erased.
what is the cause of this error and how do i resolve it?

**Comment by osborneomuya** [comment]
here is the  output of fastlane env https://github.com/fastlane/fastlane/issues/16591#issuecomment-642171839

**Comment by bffcorreia** [comment]
Hey @osborneomuya! 

Not sure why the `client-secret.json` content is erased when you run the command. Internally, we are just using `gcloud` to execute the command `auth activate-service-account`.

Nevertheless, you don't need to have your `client-secret.json` in your project. You just need to create a `.env` file with the key. Please refer to [this](https://medium.com/pink-room-club/android-continuous-integration-using-fastlane-and-circleci-2-0-part-i-7204e2e7b8b).

Hope it helps :)

**Comment by osborneomuya** [comment]
the client-secret.json is added when I run the command. Its like its downloaded to the root of the project everytime I run the command and am not sure why.i already added the .env file before running the command.

**Comment by osborneomuya** [comment]
Is there any point that the client-secret.json is downloaded when running 'bundle _exec fastlane instrumentation_tests_testlab'

**Comment by bffcorreia** [comment]
hey @osborneomuya sorry for my late response. The plugin doesn't download that file. The file is probably being created by a `gcloud` command. I need to setup a local project to test it. I can also try to schedule a call with you so I can see how can help you.
