### ISSUE TITLE
circleci apk upload to firebase testlab failure.

### ISSUE THREAD

**Issue by winphyoethu** [pink-room/fastlane-plugin-run_tests_firebase_testlab#25]
tee instrumentation_output.txt < testlab-pipe & gcloud firebase test android run --type instrumentation --app app/build/outputs/apk/debug/app-debug.apk --test app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk --device model=Pixel2,version=29,locale=en_US,orientation=portrait --timeout 30m  > testlab-pipe 2>&1
[15:47:53]: ▸ Have questions, feedback, or issues? Get support by visiting:
[15:47:53]: ▸ https://firebase.google.com/support/
[15:47:53]: ▸ Uploading [app/build/outputs/apk/debug/app-debug.apk] to Firebase Test Lab...
[15:47:53]: ▸ ERROR: (gcloud.firebase.test.android.run) [app/build/outputs/apk/debug/app-debug.apk] not found or not accessible

Hi, I am working on instrumentation test using firebase testlab on circleci. but i am getting this error whenever i run "bundle exec fastlane instrumentation_test". I am following the article you described. Please kindly help me.

**Comment by bffcorreia** [comment]
Hi @winphyoethu,

As the error suggests the `app-debug.apk` doesn't exist or isn't accessible. Can you verify if the apk is generated in the mentioned folder? Maybe has other name or other path?

You can change the apk path by overriding the `app_apk` parameter.

Let me know if you still have any doubt.

**Comment by winphyoethu** [comment]
I changed the application build path to root folder and now it is working fine. at first, my application build path is under **app/build/outputs/apk/debug/app-debug.apk**. I can run the test in local but not in circleci docker image. I think it is because of circleci docker image directory access. 

Thank you for your help.

**Comment by bffcorreia** [comment]
Cool @winphyoethu :) I will close this issue, then. Feel free to open it if you still need any help.

**Comment by winphyoethu** [comment]
Thank you for your support @bffcorreia. :)
