### ISSUE TITLE
Breaks for Windows

### ISSUE THREAD

**Issue by KyleBastien** [pink-room/fastlane-plugin-run_tests_firebase_testlab#3]
```
[!] Exit status of command 'gcloud firebase test android run --type instrumentation --app app/build/outputs/apk/debug/app-debug.apk --test app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk --device model=Nexus6P,version=27,locale=en_US,orientation=portrait --timeout 30m  2>&1 | tee instrumentation_output.txt' was 255 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
'tee' is not recognized as an internal or external command,
operable program or batch file.
```

This currently doesn't work for Windows machines because it requires the `tee` command I believe.

**Comment by bffcorreia** [comment]
Hello @KyleMcNutt 

We are using `tee` to redirect the output of the `gcloud` command to the console and also to a file. To workaround this error on Windows you can use the PowerShell or install a port of the unix `tee`.

More info [here](https://superuser.com/questions/278115/windows-command-line-redirection-to-text-file-while-also-seeing-output).
