### ISSUE TITLE
Allow starting tests for multiple device configurations

### ISSUE THREAD

**Issue by lukicmarko** [pink-room/fastlane-plugin-run_tests_firebase_testlab#7]
Add feature for passing array of devices and other device_configuration params:
```
run_tests_firebase_testlab(
        project_id: "projectid",
        model: "Nexus6P,sailfish,victara",
        version: "27,28,19",
        locale: "en_US,en_US,en_US",
        orientation: "portrait,portrait,portrait",
        gcloud_service_key_file: "key.json",
        app_apk:"./app-staging-debug.apk",
        android_test_apk:"./app-staging-debug-androidTest.apk",
        output_dir: "./instrumentationStagingTestResults")
```

**Comment by bffcorreia** [comment]
This feature is now available in version [0.3.0](https://rubygems.org/gems/fastlane-plugin-run_tests_firebase_testlab/versions/0.3.0) 🙂 We changed the lane to receive a list of `devices`, please check the [README](https://github.com/pink-room/fastlane-plugin-run_tests_firebase_testlab/blob/master/README.md) file. The `model`, `version`, `locale` and `orientation` parameters are now deprecated but we will continue to support them until the version 1.0.0.
